import { Patient, AnalyticsData, Notification } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Arjun Sharma',
    age: 45,
    gender: 'Male',
    bloodType: 'O+',
    condition: 'Cardiac Arrhythmia',
    status: 'Critical',
    doctor: 'Dr. Priya Nair',
    admissionDate: '2024-03-10',
    room: 'ICU-3',
    phone: '+91 98765 43210',
    email: 'arjun.sharma@email.com',
    insurance: 'Star Health Gold',
    lastVisit: '2024-03-10',
    nextAppointment: '2024-03-15',
    vitals: { heartRate: 112, bloodPressure: '145/95', temperature: 38.2, oxygenSaturation: 94 },
    medications: ['Amiodarone 200mg', 'Warfarin 5mg', 'Metoprolol 25mg'],
    allergies: ['Penicillin', 'Aspirin'],
    notes: 'Patient admitted with acute atrial fibrillation. Monitoring closely.'
  },
  {
    id: 'P002',
    name: 'Meera Krishnan',
    age: 32,
    gender: 'Female',
    bloodType: 'A+',
    condition: 'Type 2 Diabetes',
    status: 'Stable',
    doctor: 'Dr. Rahul Mehta',
    admissionDate: '2024-03-08',
    room: 'W-204',
    phone: '+91 87654 32109',
    email: 'meera.k@email.com',
    insurance: 'HDFC Ergo',
    lastVisit: '2024-03-08',
    nextAppointment: '2024-03-18',
    vitals: { heartRate: 78, bloodPressure: '128/82', temperature: 37.1, oxygenSaturation: 98 },
    medications: ['Metformin 500mg', 'Glimepiride 2mg', 'Vitamin D3'],
    allergies: ['Sulfa drugs'],
    notes: 'Blood glucose levels stabilizing. Diet management in progress.'
  },
  {
    id: 'P003',
    name: 'Rajesh Patel',
    age: 58,
    gender: 'Male',
    bloodType: 'B-',
    condition: 'Hypertension',
    status: 'Recovering',
    doctor: 'Dr. Anita Gupta',
    admissionDate: '2024-03-05',
    room: 'W-108',
    phone: '+91 76543 21098',
    email: 'r.patel@email.com',
    insurance: 'Max Bupa',
    lastVisit: '2024-03-05',
    nextAppointment: '2024-03-20',
    vitals: { heartRate: 68, bloodPressure: '138/88', temperature: 36.8, oxygenSaturation: 97 },
    medications: ['Amlodipine 10mg', 'Telmisartan 40mg', 'Aspirin 75mg'],
    allergies: [],
    notes: 'BP well controlled. Planning discharge by end of week.'
  },
  {
    id: 'P004',
    name: 'Sunita Verma',
    age: 28,
    gender: 'Female',
    bloodType: 'AB+',
    condition: 'Appendicitis (Post-op)',
    status: 'Recovering',
    doctor: 'Dr. Vikram Singh',
    admissionDate: '2024-03-11',
    room: 'S-302',
    phone: '+91 65432 10987',
    email: 'sunita.v@email.com',
    insurance: 'Bajaj Allianz',
    lastVisit: '2024-03-11',
    nextAppointment: '2024-03-17',
    vitals: { heartRate: 74, bloodPressure: '118/75', temperature: 37.4, oxygenSaturation: 99 },
    medications: ['Cefuroxime 500mg', 'Paracetamol 650mg', 'Pantoprazole 40mg'],
    allergies: ['Ibuprofen'],
    notes: 'Post-laparoscopic appendectomy. Wound healing well.'
  },
  {
    id: 'P005',
    name: 'Mohammed Ali Khan',
    age: 67,
    gender: 'Male',
    bloodType: 'O-',
    condition: 'COPD',
    status: 'Critical',
    doctor: 'Dr. Priya Nair',
    admissionDate: '2024-03-09',
    room: 'ICU-1',
    phone: '+91 54321 09876',
    email: 'ma.khan@email.com',
    insurance: 'New India Assurance',
    lastVisit: '2024-03-09',
    nextAppointment: '2024-03-16',
    vitals: { heartRate: 98, bloodPressure: '150/98', temperature: 38.5, oxygenSaturation: 88 },
    medications: ['Salbutamol inhaler', 'Ipratropium', 'Prednisolone 40mg', 'Oxygen therapy'],
    allergies: ['Beta-blockers'],
    notes: 'Acute exacerbation of COPD. On non-invasive ventilation.'
  },
  {
    id: 'P006',
    name: 'Kavya Reddy',
    age: 24,
    gender: 'Female',
    bloodType: 'A-',
    condition: 'Migraine',
    status: 'Stable',
    doctor: 'Dr. Rahul Mehta',
    admissionDate: '2024-03-12',
    room: 'W-215',
    phone: '+91 43210 98765',
    email: 'kavya.r@email.com',
    insurance: 'Religare Health',
    lastVisit: '2024-03-12',
    nextAppointment: '2024-03-19',
    vitals: { heartRate: 72, bloodPressure: '110/70', temperature: 36.9, oxygenSaturation: 99 },
    medications: ['Sumatriptan 50mg', 'Topiramate 25mg', 'Magnesium supplements'],
    allergies: ['Codeine'],
    notes: 'Chronic migraine management. Responsive to current treatment.'
  },
  {
    id: 'P007',
    name: 'Deepak Nambiar',
    age: 52,
    gender: 'Male',
    bloodType: 'B+',
    condition: 'Kidney Stones',
    status: 'Discharged',
    doctor: 'Dr. Vikram Singh',
    admissionDate: '2024-03-01',
    room: 'Discharged',
    phone: '+91 32109 87654',
    email: 'deepak.n@email.com',
    insurance: 'Oriental Insurance',
    lastVisit: '2024-03-07',
    nextAppointment: '2024-03-28',
    vitals: { heartRate: 70, bloodPressure: '122/78', temperature: 36.7, oxygenSaturation: 98 },
    medications: ['Tamsulosin 0.4mg', 'Potassium citrate', 'Diclofenac 50mg'],
    allergies: [],
    notes: 'Successfully passed 6mm stone. Follow-up in 3 weeks.'
  },
  {
    id: 'P008',
    name: 'Lakshmi Iyer',
    age: 39,
    gender: 'Female',
    bloodType: 'O+',
    condition: 'Hypothyroidism',
    status: 'Stable',
    doctor: 'Dr. Anita Gupta',
    admissionDate: '2024-03-13',
    room: 'W-110',
    phone: '+91 21098 76543',
    email: 'lakshmi.i@email.com',
    insurance: 'ICICI Lombard',
    lastVisit: '2024-03-13',
    nextAppointment: '2024-03-22',
    vitals: { heartRate: 64, bloodPressure: '115/72', temperature: 36.6, oxygenSaturation: 98 },
    medications: ['Levothyroxine 75mcg', 'Calcium supplements', 'Vitamin B12'],
    allergies: ['Iodine contrast'],
    notes: 'TSH levels being monitored. Dosage adjustment pending lab results.'
  }
];

export const mockAnalytics: AnalyticsData = {
  admissions: [
    { month: 'Sep', count: 142 },
    { month: 'Oct', count: 168 },
    { month: 'Nov', count: 155 },
    { month: 'Dec', count: 189 },
    { month: 'Jan', count: 201 },
    { month: 'Feb', count: 178 },
    { month: 'Mar', count: 215 },
  ],
  departments: [
    { name: 'Cardiology', patients: 48, beds: 60 },
    { name: 'Neurology', patients: 35, beds: 40 },
    { name: 'Orthopedics', patients: 62, beds: 70 },
    { name: 'Oncology', patients: 29, beds: 35 },
    { name: 'Pediatrics', patients: 41, beds: 50 },
    { name: 'Emergency', patients: 78, beds: 80 },
  ],
  outcomes: [
    { status: 'Recovered', value: 68, color: '#22c55e' },
    { status: 'Stable', value: 19, color: '#3b82f6' },
    { status: 'Critical', value: 8, color: '#ef4444' },
    { status: 'Discharged', value: 5, color: '#a855f7' },
  ],
  revenue: [
    { month: 'Sep', revenue: 42, expenses: 28 },
    { month: 'Oct', revenue: 51, expenses: 32 },
    { month: 'Nov', revenue: 47, expenses: 30 },
    { month: 'Dec', revenue: 58, expenses: 35 },
    { month: 'Jan', revenue: 63, expenses: 38 },
    { month: 'Feb', revenue: 55, expenses: 33 },
    { month: 'Mar', revenue: 71, expenses: 41 },
  ]
};

export const mockNotifications: Notification[] = [
  { id: 'N001', title: 'Critical Alert', message: 'Patient P005 oxygen saturation dropped to 88%', type: 'alert', timestamp: '2024-03-13T09:15:00', read: false },
  { id: 'N002', title: 'Lab Results Ready', message: 'Blood panel results for Arjun Sharma are available', type: 'info', timestamp: '2024-03-13T08:45:00', read: false },
  { id: 'N003', title: 'Appointment Reminder', message: 'Dr. Mehta has 3 appointments in the next hour', type: 'warning', timestamp: '2024-03-13T08:00:00', read: true },
  { id: 'N004', title: 'Discharge Approved', message: 'Deepak Nambiar discharge process completed', type: 'success', timestamp: '2024-03-13T07:30:00', read: true },
];
